name: Fuzz-Simple

on:
  workflow_dispatch:

jobs:
  run-fuzz:
    runs-on: ubuntu-latest

    env:
      MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
      MARIADB_USER: ${{ secrets.MARIADB_USER }}
      MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
      FLAG_2: ${{ secrets.FLAG_2 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest

      - name: Start application with Docker Compose
        run: |
          docker compose up -d --build || true
          sleep 20
          docker ps -a

      - name: Show DB logs
        run: docker compose logs db || true

      - name: Run simple fuzzer
        run: |
          python fuzz/simple_fuzzer.py || echo "Fuzzer failed but continuing..."

      - name: Collect logs
        run: |
          mkdir -p artifacts
          docker compose logs server > artifacts/fuzz_server_logs.txt || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-logs
          path: artifacts
